# docker-compose.yml for Flame Training (Dev Mode)
#
# Make your own entrypoint first, here are three examples:
#   /entrypoint-base.sh  - No flame, no lm-evaluation-harness, just verification of GPU setup and a clean environment for debugging
#   /entrypoint-flame.sh - Install Adrian's flame
#   /entrypoint-full.sh  - Install Adrian's flame + Adrian's lm-evaluation-harness 
#   /entrypoint-razel.sh 
#
# Usage:
#   docker-compose up -d Razel
#   docker exec -it razel bash
#   docker-compose down Razel    # Must mention the service name to avoid taking down all containers

# ----- Shared config -----
x-common: &common
  image: daal/flame-qwen35:v0
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  ipc: host
  ulimits:
    memlock: -1
    stack: 67108864
  network_mode: host
  environment: &common-env
    - NGPU=8
    - CUDA_DEVICE_ORDER=PCI_BUS_ID
    - NCCL_DEBUG=WARN
    - HF_HOME=/home/.cache/huggingface  # share HF_HOME to avoid redundent dataset caches
    - WANDB_API_KEY=${WANDB_API_KEY:-}
    - WANDB_PROJECT=flame-training
    - MASTER_ADDR=${MASTER_ADDR:-localhost}
    - MASTER_PORT=${MASTER_PORT:-29500}
  volumes:
    - /home:/home
  working_dir: /home
  stdin_open: true
  tty: true
  restart: unless-stopped
  command: /bin/bash

services:
  # Razel's service and container
  Razel:
    <<: *common
    container_name: razel
    entrypoint: /home/docker/entrypoint-basic.sh


  # Sandeep's service and container
  Sandeep: # service name
    <<: *common
    container_name: sandeep # container name
    entrypoint: /home/docker/entrypoint-basic.sh

  # Adrian's service and contianer
  Adrian:
    <<: *common
    container_name: adrian
    entrypoint: /home/docker/entrypoint-flame.sh